=== Ronak2247232/CAT1/empschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">>
<xs:element name="company">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="employee">
            <xs:complexType>  
                <xs:sequence>
                    <xs:element name="Emp-name" type="xs:string"/>
                    <xs:element name="Emp-age" type="xs:integer"/>
                    <xs:element name="Emp-salary">
                    <xs:simpleType>
                    <restriction base="xs:integer">
                        <minInclusive value="50000"/>
                        <maxInclusive value="200000"/>
                    </restriction>
                    </xs:simpleType>
                    </xs:element>
                    <xs:element name="Emp-emailid" type="xs:string"/>
                    <xs:element name="Emp-phonenum" type="xs:integer"/>
                    <xs:element name="Emp-designation" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Ronak2247232/CAT1/emp.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="empstyle.xsl"?>
<company  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="empschema.xsd">
    <employee>
    <Emp-id>01</Emp-id>
    <Emp-name>Ronak Prasad</Emp-name>
    <Emp-age>21</Emp-age>
    <Emp-salary>60000</Emp-salary>
    <Emp-emailid>ronakprasad@gmail.com</Emp-emailid>
    <Emp-phonenum>9986449127</Emp-phonenum>
    <Emp-designation>Intern</Emp-designation>
    </employee>
</company>
